spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL}
    jdbcUrl: ${spring.datasource.url}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
